In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.25447276, -0.4117162 , -0.1797627 ,  0.0367009 ,  0.08295098,
         0.18858077,  0.5445802 , -0.07630867, -0.35025734,  0.6543118 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.07123891, 0.06087336, 0.07676502, 0.09531743, 0.09982941,
        0.11095144, 0.15839502, 0.08513201, 0.06473193, 0.17676543]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.1986628

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4853 - accuracy: 0.8571
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1533 - accuracy: 0.9555
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1073 - accuracy: 0.9664
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0874 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0728 - accuracy: 0.9765


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0753 - accuracy: 0.9775


[0.07531891763210297, 0.9775000214576721]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.4939387e-08, 3.3133286e-08, 7.1809854e-06, 1.2241653e-04,
        6.9003060e-11, 2.0087779e-07, 3.3096502e-13, 9.9985445e-01,
        1.1786359e-07, 1.5558857e-05],
       [2.1645952e-09, 3.4922390e-04, 9.9964929e-01, 1.3364746e-06,
        5.2316746e-16, 1.3856587e-08, 6.4107049e-08, 4.5412028e-14,
        4.4222578e-08, 1.5844249e-13],
       [7.9676333e-08, 9.9976522e-01, 2.8387984e-05, 1.0770826e-05,
        5.8872083e-06, 7.3704274e-07, 6.8902586e-06, 1.6789556e-04,
        1.4044978e-05, 1.2751003e-07],
       [9.9850613e-01, 1.1049085e-07, 1.4046393e-03, 5.3428488e-07,
        2.3354996e-06, 1.7936183e-05, 4.1714087e-05, 2.1914528e-05,
        1.1190102e-07, 4.4786134e-06],
       [7.3370245e-07, 3.5881869e-09, 1.0800316e-05, 4.6456606e-07,
        9.5930612e-01, 1.5861385e-06, 4.2746274e-07, 2.7090163e-04,
        2.5280335e-07, 4.0408675e-02]], dtype=float32)>